import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { fileURLToPath } from 'node:url';
import { loadConfig } from '../server/config.mjs';
import { JobStore } from '../server/store.mjs';
import { createHttpApp, validateJob } from '../server/http.mjs';

async function harness(extra={}){
  const config=loadConfig({PORT:'0',...extra}),store=new JobStore(':memory:');
  const app=createHttpApp({config,store,providers:{token:async()=>({apiKey:'temporary',expiresAt:'soon'})},publicDir:fileURLToPath(new URL('../public/',import.meta.url))});
  app.listen(0,'127.0.0.1');await once(app,'listening');const base=`http://127.0.0.1:${app.address().port}`;
  return {config,store,app,base,request:(path,opts)=>fetch(base+path,opts),close:async()=>{app.closeAllConnections();await new Promise(r=>app.close(r));store.close();}};
}
const payload={kind:'tripo',mode:'demo',prompt:'A quiet seed pod',idempotencyKey:'http-test-00001'};
const headers={'Content-Type':'application/json','X-Breathe-Request':'1'};

test('health, config and native module assets are served without dependencies',async()=>{const h=await harness();try{assert.equal((await (await h.request('/api/health')).json()).ok,true);assert.equal((await (await h.request('/api/config')).json()).paidEnabled,false);const r=await h.request('/');assert.equal(r.status,200);assert.ok((await r.text()).includes('Breathe City'));assert.match((await h.request('/js/app.js')).headers.get('content-type'),/javascript/);}finally{await h.close();}});
test('server files and environment secrets cannot be fetched as static assets',async()=>{const h=await harness();try{for(const path of ['/.env','/server/config.mjs','/package.json','/%2eenv'])assert.equal((await h.request(path)).status,404);}finally{await h.close();}});
test('mutation requires request marker, valid origin and JSON',async()=>{const h=await harness();try{assert.equal((await h.request('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})).status,403);assert.equal((await h.request('/api/jobs',{method:'POST',headers:{...headers,Origin:'https://evil.example'},body:JSON.stringify(payload)})).status,403);assert.equal((await h.request('/api/jobs',{method:'POST',headers:{'X-Breathe-Request':'1','Content-Type':'text/plain'},body:'x'})).status,415);}finally{await h.close();}});
test('job create is idempotent and real mode never silently falls back to demo',async()=>{const h=await harness();try{const a=await(await h.request('/api/jobs',{method:'POST',headers,body:JSON.stringify(payload)})).json();const b=await(await h.request('/api/jobs',{method:'POST',headers,body:JSON.stringify(payload)})).json();assert.equal(a.job.id,b.job.id);assert.equal(b.reused,true);const real=await h.request('/api/jobs',{method:'POST',headers,body:JSON.stringify({...payload,mode:'real',confirmed:true,idempotencyKey:'real-test-key'})});assert.equal(real.status,403);assert.equal(h.store.list().length,1);}finally{await h.close();}});
test('configured admin token protects job reads and writes',async()=>{const token='secure-admin-token-123456789';const h=await harness({ADMIN_TOKEN:token});try{assert.equal((await h.request('/api/jobs')).status,401);const r=await h.request('/api/jobs',{headers:{Authorization:`Bearer ${token}`}});assert.equal(r.status,200);const config=JSON.stringify(await(await h.request('/api/config')).json());assert.ok(!config.includes(token));}finally{await h.close();}});
test('paid generation needs configured provider plus explicit consent',async()=>{const token='secure-admin-token-123456789';const h=await harness({ADMIN_TOKEN:token,ALLOW_PAID_APIS:'true',TRIPO_API_KEY:'a-secret'});const auth={...headers,Authorization:`Bearer ${token}`};try{const base={...payload,mode:'real'};assert.equal((await h.request('/api/jobs',{method:'POST',headers:auth,body:JSON.stringify(base)})).status,400);assert.equal((await h.request('/api/jobs',{method:'POST',headers:auth,body:JSON.stringify({...base,confirmed:true})})).status,202);assert.equal(h.store.list()[0].mode,'real');}finally{await h.close();}});
test('client token endpoint is gated and quota is enforced before upstream call',async()=>{const token='secure-admin-token-123456789';const h=await harness({ADMIN_TOKEN:token,ALLOW_PAID_APIS:'true',DECART_API_KEY:'private-key',MAX_REALTIME_TOKENS_PER_DAY:'1'});try{const opts={method:'POST',headers:{...headers,Authorization:`Bearer ${token}`},body:JSON.stringify({confirmed:true})};const r=await h.request('/api/realtime/token',opts);assert.equal(r.status,200);assert.equal((await r.json()).apiKey,'temporary');assert.equal((await h.request('/api/realtime/token',opts)).status,429);}finally{await h.close();}});
test('cancelled queued jobs stop before any external submission',async()=>{const h=await harness();try{const job=h.store.create(payload).job;const r=await h.request(`/api/jobs/${job.id}/stop`,{method:'POST',headers,body:'{}'});assert.equal((await r.json()).job.state,'cancelled');assert.equal(h.store.due(),null);}finally{await h.close();}});
test('malformed payloads are rejected instead of coerced',()=>{for(const p of [{...payload,kind:'bad'},{...payload,mode:'live'},{...payload,prompt:''},{...payload,idempotencyKey:'bad'},{}])assert.throws(()=>validateJob(p));});
test('oversized JSON is rejected before parsing',async()=>{const h=await harness();try{assert.equal((await h.request('/api/jobs',{method:'POST',headers,body:JSON.stringify({...payload,prompt:'x'.repeat(20000)})})).status,413);}finally{await h.close();}});
